name: Build

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer
    - name: make
      run: |
        sudo make
        sudo make install
    - name: test
      run: |
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE
        clang test.c -lmxml -D__PC__
        ./a.out
